# Edit this file to change IPs, ports and timing

# This node's address (must match one of the peers below for each server)
this_node = ""
# this_node = "127.0.0.1:3003"

# List of all cluster peers (including this node)
peers = [
 "10.40.45.27:5000",
 "10.40.36.216:5000",
 "10.40.54.163:5000",
]
#peers = [
#  "127.0.0.1:3001",
#  "127.0.0.1:3002",
#  "127.0.0.1:3003",
#]

# How often leader sends heartbeat (milliseconds)
heartbeat_interval_ms = 300

# If a follower misses this many milliseconds since last heartbeat, it starts election
# Randomized election timeout range (milliseconds)
# Each node will pick a random value between min and max
# Raft recommends: max should be ~2x min, and min should be 10x heartbeat_interval
election_timeout_min_ms = 9000
election_timeout_max_ms = 15000

# Duration of a leader term in milliseconds (default 2 minutes = 120,000)
leader_term_ms = 30000

# Timeout for network operations (milliseconds)
net_timeout_ms = 1000

# How often to refresh local CPU measurement (ms)
cpu_refresh_ms = 500

# Election retry wait (ms) - wait between retries to contact peers
election_retry_ms = 200